### ISSUE TITLE
Is it possible to enter data into the card?

### ISSUE THREAD

**Issue by seenewmax** [Origogi/Flutter-Credit-Card-Input-Form#10]
Hello I put this package to my favourites few months ago and trying to use it now.
Thank you for your contribution before the question.

I'm planning to save the card information and let users to see their cards filled with the information.
I tried to find how to put data into the card but I couldn't find text controller from the code.
If possible, would you tell me how I can make a card with information?

**Comment by Origogi** [comment]
@seenewmax 

Thx ur approach!

I think that It is a new feature. 
please wait some hour! I will improve this plug in

**Comment by seenewmax** [comment]
I will! I appreciate your quick response!

**Comment by Origogi** [comment]
@seenewmax 

I updated new version!

https://github.com/Origogi/Flutter-Credit-Card-Input-Form#v210

plz check it

**Comment by seenewmax** [comment]
Just checked! Thank you so much, good night!
