### ISSUE TITLE
Card number overflow

### ISSUE THREAD

**Issue by seenewmax** [Origogi/Flutter-Credit-Card-Input-Form#11]
![overflow](https://user-images.githubusercontent.com/37838834/96216642-c1397000-0fbb-11eb-9e7d-b5db5c97bc1f.png)

Font size of card number seems fixed, so it overflows in smaller devices like iPhone SE.

**Comment by Origogi** [comment]
Thx report!. 
I will fixed it

**Comment by Origogi** [comment]
@seenewmax 
I fixed overflow problem

plz update last version(v2.1.3)
![Simulator Screen Shot - iPhone SE1 - 2020-10-19 at 22 47 22](https://user-images.githubusercontent.com/35194820/96459468-1e078580-125d-11eb-8c6f-5f3ba2ce987c.png)
