### ISSUE TITLE
Text field bottom overflow

### ISSUE THREAD

**Issue by ghost** [Origogi/Flutter-Credit-Card-Input-Form#12]
With a Samsung text field bottom overflow 4 pixels

![card_overflow](https://user-images.githubusercontent.com/22193771/103284669-1e9a6600-49dc-11eb-8402-23002d4e508b.jpg)

Thank you

**Comment by Origogi** [comment]
I update this plug in v2.1.4
please test using lastest version

https://pub.dev/packages/credit_card_input_form

**Comment by ghost** [comment]
Working !
Thank you
