### ISSUE TITLE
Error if text entered

### ISSUE THREAD

**Issue by ghost** [Origogi/Flutter-Credit-Card-Input-Form#14]
It's possible to enter text in card number field (with some phones or with a copy/paste) = Red screen.
Thank you

![carte_Err](https://user-images.githubusercontent.com/22193771/104816146-6fea8800-5819-11eb-9938-af8f6c23e068.jpg)

**Comment by Origogi** [comment]
I fixed it 

plz download lastest version
credit_card_input_form 2.1.5

**Comment by ghost** [comment]
Always possible to enter a point "."

![point](https://user-images.githubusercontent.com/22193771/104840154-e8a71e00-58c5-11eb-8155-2afdf0ebbb39.jpg)

**Comment by Origogi** [comment]
i fixed it
check v2.1.6

**Comment by ghost** [comment]
HEllo,
unfortunately no. When I enter a point (.) the field is in error red
BR

![card_input](https://user-images.githubusercontent.com/22193771/105026044-66963100-5a4e-11eb-93cd-53da31e2b1e2.jpg)

**Comment by Origogi** [comment]
![11111](https://user-images.githubusercontent.com/35194820/105131599-99aef200-5b2c-11eb-9d00-dac131549dba.gif)

Hello I checked lastest version.

so when user input dot character(.) in keyboard, but ignore this input, and did not crash 

could you check version (2.1.6)?

**Comment by ghost** [comment]
With 2.1.6:

https://user-images.githubusercontent.com/22193771/105173542-77fc3d80-5b21-11eb-80d7-58f78831a513.mp4

**Comment by Origogi** [comment]
ok i see. 
plz attached crash log
I want to know what number code line was occurred crash when input dot char

**Comment by ghost** [comment]
Sorry for the delay...


The following assertion was thrown building InputForm(dirty, state: _InputFormState#e93a2):
New TextEditingValue TextEditingValue(text: ┤4242├, selection: TextSelection(baseOffset: 4,
extentOffset: 4, affinity: TextAffinity.downstream, isDirectional: false), composing:
TextRange(start: 4, end: 5)) has an invalid non-empty composing range TextRange(start: 4, end: 5).
It is recommended to use a valid composing range, even for readonly text fields
'package:flutter/src/widgets/editable_text.dart':
Failed assertion: line 170 pos 7: '!newValue.composing.isValid || newValue.isComposingRangeValid'

The relevant error-causing widget was:
  InputForm
  file:///Users/zozo/flutter/.pub-cache/hosted/pub.dartlang.org/credit_card_input_form-2.1.6/lib/components/input_view_pager.dart:67:24


When the exception was thrown, this was the stack:
#2      TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:170:7)
#3      _InputFormState.build (package:credit_card_input_form/components/input_view_pager.dart:197:19)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#18     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#22     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#27     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#31     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#33     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1158:36)
#34     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1076:34)
#35     Iterable.forEach (dart:core/iterable.dart:283:30)
#36     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1116:24)
#37     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1055:7)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#43     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#45     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
#46     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
#47     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:231:11)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#57     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#62     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#64     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#70     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#74     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#76     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#86     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#91     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#94     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#96     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#100    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#103    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#105    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#107    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#111    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#114    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#116    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#121    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#123    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#125    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
#126    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#128    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
#129    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#132    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#133    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#134    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
D/InputMethodManager(15315): HSIFW - flag : 0
I/ViewRootImpl@ea88e6e[MainActivity](15315): MSG_RESIZED: frame=(0,0,1080,2400) ci=(0,79,0,126) vi=(0,79,0,126) or=1
I/ViewRootImpl@ea88e6e[MainActivity](15315): Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=4 res=0x1 s={true 500943298560} ch=false
#135    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
#136    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#137    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#138    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#139    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
#143    _invoke (dart:ui/hooks.dart:251:10)
#144    _drawFrame (dart:ui/hooks.dart:209:3)
(elided 5 frames from class _AssertionError and dart:async)

══════════════════════════════════════════════════
Another exception was thrown: New TextEditingValue TextEditingValue(text: ┤4242├, selection: TextSelection(baseOffset: 4, extentOffset: 4, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 4, end: 5)) has an invalid non-empty composing range TextRange(start: 4, end: 5). It is recommended to use a valid composing range, even for readonly text fields
Another exception was thrown: New TextEditingValue TextEditingValue(text: ┤4242├, selection: TextSelection(baseOffset: 4, extentOffset: 4, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 4, end: 5)) has an invalid non-empty composing range TextRange(start: 4, end: 5). It is recommended to use a valid composing range, even for readonly text fields
