### ISSUE TITLE
Set AutoFocus Value

### ISSUE THREAD

**Issue by moesaif** [Origogi/Flutter-Credit-Card-Input-Form#16]
Hello and Thank you for this great library , my only issue is that the widget is autofocused by default so how can i possibly set autofocus to false

**Comment by Origogi** [comment]
@moesaif 
it is new feature, i will implement it

**Comment by Origogi** [comment]
I add new parameter `initialAutoFoucus'

please download lastest version(v2.2.0)

~~~ dart
CreditCardInputForm(
                ...
                initialAutoFocus: false,
                ...
~~~

**Comment by moesaif** [comment]
Thanks Bro
