### ISSUE TITLE
null-safety

### ISSUE THREAD

**Issue by ghost** [Origogi/Flutter-Credit-Card-Input-Form#18]
Do you plan to update null-safety ?
thank you ?

**Comment by Origogi** [comment]
@Cyphontin 

Sorry I'm late

Could you explain null-safety?? 

For example, have you ever encountered a null exception during plug-in operation?

**Comment by ghost** [comment]
It's not compatible with Flutter 2.

environment:
  sdk: '>=2.12.1 <3.0.0' # Flutter 2

type in terminal:   dart pub outdated --mode=null-safety

Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name            Current  Upgradable  Resolvable  Latest  
direct dependencies:   
credit_card_input_form  ✗2.2.0   ✗2.2.0      ✗2.2.0      ✗2.2.0

**Comment by Origogi** [comment]
@Cyphontin 
I updated new plugin(v2.3.0) that migration flutter 2.0
