### ISSUE TITLE
How to change text in credit. card input form

### ISSUE THREAD

**Issue by Shradak** [Origogi/Flutter-Credit-Card-Input-Form#19]
How can i change the card text and text of next previous button in credit card input form library plz suggest 
<img width="923" alt="Screenshot 2021-10-28 at 11 17 23 AM" src="https://user-images.githubusercontent.com/92969297/139195021-d8b2f624-4f97-463f-8546-7f1bbefe6b39.png">
<img width="917" alt="Screenshot 2021-10-28 at 11 17 44 AM" src="https://user-images.githubusercontent.com/92969297/139195031-d568470d-3744-43f7-972f-b4a7ac38d134.png">

**Comment by Origogi** [comment]
Sorry I'm rate

![image](https://user-images.githubusercontent.com/35194820/139824747-f765bdf2-cadf-4a0d-84fd-00d24e991001.png)

plz change value of 'PREV' and 'NEXT'  key

example 
~~~dart
  final Map<String, String> customCaptions = {
    'PREV': 'CustomPrev',
    'NEXT': 'customNext',
    ...
  };

~~~
