### ISSUE TITLE
Edit card after adding button DONE

### ISSUE THREAD

**Issue by alanjholiveira** [Origogi/Flutter-Credit-Card-Input-Form#2]
Do you have any option to edit the card after clicking "DONE".?
When I go to DONE the fields disappear so I can't edit it if I typed the wrong number on the card.

**Comment by Origogi** [comment]
@alanjholiveira 
Hello. above issue is a new feature, so I think that add `RESET` button after click `DONE`

is it right? if u have any idea, notify to me

**Comment by alanjholiveira** [comment]
How about enabling an EDIT button on top of the DONE button. What do you think?

**Comment by Origogi** [comment]
hmm.. when user touch `EDIT` button, Widget move previous state(CVV). 
is it right??

**Comment by alanjholiveira** [comment]
There is no button(EDIT) implemented. 
Implement a button that clears/edit the field and enables typing again

**Comment by Origogi** [comment]
Ok. i see.. 
I imple edit function, and deploy next version

**Comment by Origogi** [comment]
@alanjholiveira 

hello, plug in update v1.1.1

https://pub.dev/packages/credit_card_input_form

![image](https://user-images.githubusercontent.com/35194820/85917842-9aceb800-b898-11ea-8648-29870021ccfc.png)

~~~dart
CreditCardInputForm(
              showResetButton: true,
              onStateChange: (currentState, cardInfo) {
                print(currentState);
                print(cardInfo);
              },
            ),
~~~
