### ISSUE TITLE
Customize buttons

### ISSUE THREAD

**Issue by luccascorrea** [Origogi/Flutter-Credit-Card-Input-Form#4]
Hi, thanks for the awesome lib!

One question, is there a way to customize the prev and next buttons? I was checking out the source code and it seems like there isn't. Are there plans to enable this?

Thanks!

**Comment by Origogi** [comment]
do u want change color or size?

**Comment by luccascorrea** [comment]
It would be great to be able to change the styling of the button in general (color, format, text size). Thanks!

**Comment by Origogi** [comment]
@luccascorrea 
I added new feature!

please check readme and update plugin version

https://github.com/Origogi/Flutter-Credit-Card-Input-Form#new-feature

**Comment by luccascorrea** [comment]
Great work! Thank you @Origogi
