### ISSUE TITLE
Done button pressed

### ISSUE THREAD

**Issue by mannevin** [Origogi/Flutter-Credit-Card-Input-Form#5]
Is there a way to do something separate from the credit card when the done button is pressed? Essentially, I want to call 'onPressed'

**Comment by Origogi** [comment]
@mannevin sorry, I could not understand ur issue. 
Please let me know in more detail

**Comment by Origogi** [comment]
@mannevin i understand issue to read email. 

you focus `onStateChange` callback

~~~dart
CreditCardInputForm(
                onStateChange: (currentState, cardInfo) {
                  print(currentState);
                  print(cardInfo);
                },
}
~~~

if u pressed `DONE` button
flutter would print below debug message
> flutter: InputState.DONE
