### ISSUE TITLE
AMEX CVC

### ISSUE THREAD

**Issue by ghost** [Origogi/Flutter-Credit-Card-Input-Form#6]
Amex cards have a 4 digit CVC, only 3 possible

**Comment by Origogi** [comment]
ok i see. i change that able to input 4 digit CVC

**Comment by Origogi** [comment]
@Cyphontin 
I fix above issue. 

please to update plug in lastest version

[Note](https://pub.dev/packages/credit_card_input_form/changelog#203)

**Comment by ghost** [comment]
Thank you
